network:
  num_blocks: 3
  num_seg_class: 2  # 0: background, 1: myocardium
  rescale_factor: 0.1
  input_size:
    - 128
    - 128
    - 128
  hidden_dim: 128
  coord_emb_dim: 384
prediction:
  model_weights_filename: /path/to/pretrained/task1_mmwhs.hdf5 
  image:
    image_folder: /path/to/MMWHS/nii/
    image_folder_attr: _test
    modality:
      - ct
  mesh:
    mesh_dat_filemame: templates/meshes/??_??_20??_??_??_??_bbw.dat
    mesh_tmplt_filename: templates/meshes/??_??_20??_??_??_??_template.vtp
    swap_bc_coordinates: null
    num_mesh: 1     # equals the number of template mesh
  output_folder: /path/to/output/
  mode: test
train:
    batch_size: 1
    lr: 0.0005
    num_epoch: 300
    pre_train: null
    pre_train_unet: null
    mesh_dat_filemame: templates/meshes/??_??_20??_??_??_??_bbw.dat
    data:
        train_img_folder:
            - /path/to/MMWHS/tfrecords_augmented/
        val_img_folder: 
            - /path/to/MMWHS/tfrecords/
        file_pattern: '*.tfrecords'
        train_sub_folder_attr: ['']
        val_sub_folder_attr: ['']
        train_sub_folder_weights: [1.]
        val_sub_folder_weights: [1.] 
        mesh_ids: [0]   # myocardium
        modality: 
            - ct
        seed: 42
    loss:
        seg_wt: 100
        geom_wt: [0.3, 0.46, 25.]
        mesh_wt: [0.5, 0.5, 0.5]
        chamfer_ratio: 1.
        if_mask: True
        if_cap: False
        turn_off_l2: False
    output_folder: /path/to/output/

